### ISSUE TITLE
respect utf8

### ISSUE THREAD

**Issue by KES777** [frioux/DBIx-Class-DeploymentHandler#65] opened 2019-03-05 17:20 UTC
described here: https://github.com/jjn1056/DBIx-Class-Migration/issues/108

**Comment by mohawk2** [comment] 2019-03-07 08:03
@KES777 Thanks for reporting this on here and SQLT as asked. Sadly I am entirely sure this is an SQLT/Moose interaction (which seems to zap imported things, which may explain the zapping of `utf8` only on Moose DBIC classes), so unless you provide steps that prove the problem is in DH, no action is possible.

Closing until that is provided.

**Closed by mohawk2** 2019-03-07 08:03 UTC

**Comment by KES777** [comment] 2025-04-07 03:28
@mohawk2 Hi. Steps were provided. 3 additional tests were written for DBICM, DBICDH and SQLT. See the linked PR 82 
I hope they will help to understand the problem better.
